# Generated by Django 4.0.4 on 2022-05-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=10, null=True, verbose_name='Phone')),
                ('internship', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=8, verbose_name='Internship')),
                ('college', models.CharField(blank=True, max_length=50, null=True, verbose_name='College')),
                ('team', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=8, verbose_name='Team')),
                ('represent', models.CharField(blank=True, max_length=50, null=True, verbose_name='Represent')),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email')),
            ],
        ),
    ]
