# Generated by Django 4.0.4 on 2022-05-11 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AVITAIndia', '0002_rename_campu_campus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Campus',
            new_name='Campu',
        ),
        migrations.RenameModel(
            old_name='Countries',
            new_name='Countrie',
        ),
    ]
