# Generated by Django 4.0.4 on 2022-05-11 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='New',
        ),
        migrations.AlterField(
            model_name='banner',
            name='url',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Url'),
        ),
    ]
