# Generated by Django 4.0.4 on 2022-05-16 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Articles', '0002_rename_news_new_alter_banner_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image_path',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/Banner/mob', verbose_name='Mob Image'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='thumbnail_path',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/Banner/web', verbose_name='Web Image'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image_path',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/Banner/mob', verbose_name='Mob Image'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='thumbnail_path',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/Banner/web', verbose_name='Web Image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='image_path',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/Event/mob', verbose_name='Mob Image'),
        ),
        migrations.AlterField(
            model_name='event',
            name='thumbnail_path',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/Event/web', verbose_name='Web Image'),
        ),
        migrations.AlterField(
            model_name='new',
            name='image_path',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/News/mob', verbose_name='Mob Image'),
        ),
        migrations.AlterField(
            model_name='new',
            name='thumbnail_path',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/News/web', verbose_name='Web Image'),
        ),
    ]
