# Generated by Django 4.0.4 on 2022-05-11 05:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('models_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Product Model Number')),
            ],
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Type Name')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Product Series')),
                ('product_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.producttype')),
            ],
        ),
        migrations.CreateModel(
            name='ProductNumbers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Product_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Product Number')),
                ('product_configuration', models.CharField(blank=True, max_length=50, null=True, verbose_name='Product Configuration')),
                ('product_model_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.productmodels')),
            ],
        ),
        migrations.AddField(
            model_name='productmodels',
            name='product_series_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.productseries'),
        ),
    ]
