# Generated by Django 4.0.4 on 2022-05-11 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0002_rename_product_number_productnumbers_product_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductModels',
            new_name='ProductModel',
        ),
        migrations.RenameModel(
            old_name='ProductNumbers',
            new_name='ProductNumber',
        ),
        migrations.RenameModel(
            old_name='ProductSeries',
            new_name='ProductSerie',
        ),
    ]
