# Generated by Django 4.0.4 on 2022-05-10 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0002_alter_servicecenters_id_alter_wheretobuys_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecenters',
            name='address',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='servicecenters',
            name='city',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='servicecenters',
            name='country',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Country '),
        ),
        migrations.AlterField(
            model_name='servicecenters',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='servicecenters',
            name='latitude',
            field=models.FloatField(blank=True, max_length=50, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='servicecenters',
            name='locale',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Locale'),
        ),
        migrations.AlterField(
            model_name='servicecenters',
            name='longitude',
            field=models.FloatField(blank=True, max_length=50, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='servicecenters',
            name='phone',
            field=models.TextField(blank=True, max_length=10, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='servicecenters',
            name='pin',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Pin'),
        ),
        migrations.AlterField(
            model_name='servicecenters',
            name='state',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='wheretobuys',
            name='address',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='wheretobuys',
            name='city',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='wheretobuys',
            name='country',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Country '),
        ),
        migrations.AlterField(
            model_name='wheretobuys',
            name='email',
            field=models.EmailField(blank=True, max_length=50, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='wheretobuys',
            name='latitude',
            field=models.FloatField(blank=True, max_length=50, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='wheretobuys',
            name='locale',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Locale'),
        ),
        migrations.AlterField(
            model_name='wheretobuys',
            name='longitude',
            field=models.FloatField(blank=True, max_length=50, null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='wheretobuys',
            name='phone',
            field=models.TextField(blank=True, max_length=10, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='wheretobuys',
            name='pin',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Pin'),
        ),
        migrations.AlterField(
            model_name='wheretobuys',
            name='state',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='State'),
        ),
    ]
