# Generated by Django 4.0.4 on 2022-05-10 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0003_alter_servicecenters_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecenters',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='servicecenters',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Country '),
        ),
        migrations.AlterField(
            model_name='servicecenters',
            name='locale',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Locale'),
        ),
        migrations.AlterField(
            model_name='servicecenters',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='servicecenters',
            name='pin',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pin'),
        ),
        migrations.AlterField(
            model_name='servicecenters',
            name='shop_Name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Shop Name'),
        ),
        migrations.AlterField(
            model_name='servicecenters',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='wheretobuys',
            name='city',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='wheretobuys',
            name='country',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Country '),
        ),
        migrations.AlterField(
            model_name='wheretobuys',
            name='locale',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Locale'),
        ),
        migrations.AlterField(
            model_name='wheretobuys',
            name='phone',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='wheretobuys',
            name='pin',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Pin'),
        ),
        migrations.AlterField(
            model_name='wheretobuys',
            name='shop_Name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Shop Name'),
        ),
        migrations.AlterField(
            model_name='wheretobuys',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='State'),
        ),
    ]
