# Generated by Django 4.0.4 on 2022-05-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0005_rename_wheretobuys_servicecenter_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicecenter',
            name='address',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='servicecenter',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='servicecenter',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country '),
        ),
        migrations.AlterField(
            model_name='servicecenter',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='servicecenter',
            name='opening_hour',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='opening_hour'),
        ),
        migrations.AlterField(
            model_name='servicecenter',
            name='shop_Name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Shop Name'),
        ),
        migrations.AlterField(
            model_name='servicecenter',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='wheretobuy',
            name='address',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='wheretobuy',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='wheretobuy',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Country '),
        ),
        migrations.AlterField(
            model_name='wheretobuy',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='wheretobuy',
            name='opening_hour',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='opening_hour'),
        ),
        migrations.AlterField(
            model_name='wheretobuy',
            name='shop_Name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Shop Name'),
        ),
        migrations.AlterField(
            model_name='wheretobuy',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='State'),
        ),
    ]
