# Generated by Django 4.0.4 on 2022-05-10 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField(blank=True, max_length=50, null=True, verbose_name='User ID')),
                ('order_id', models.TextField(blank=True, max_length=50, null=True, verbose_name='Order ID')),
                ('product_configuration', models.CharField(blank=True, max_length=50, null=True, verbose_name='Product Configuration')),
                ('product_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Product Number')),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Serial Number')),
                ('reseller_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Reseller Name')),
                ('purchase_date', models.DateField(blank=True, max_length=50, null=True, verbose_name='Purchase Date')),
                ('extend_date', models.DateField(blank=True, max_length=50, null=True, verbose_name='Extend Date')),
            ],
        ),
        migrations.CreateModel(
            name='WarrantyExtend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField(blank=True, max_length=50, null=True, verbose_name='User ID')),
                ('product_number_id', models.TextField(blank=True, max_length=50, null=True, verbose_name='Product Number')),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Serial Number')),
                ('reseller_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Reseller Name')),
                ('purchase_date', models.DateField(blank=True, max_length=50, null=True, verbose_name='Purchase Date')),
                ('purchase_invoice', models.FileField(blank=True, max_length=50, null=True, upload_to='media/images/purchase_invoice', verbose_name='Purchase Invoice')),
            ],
        ),
        migrations.CreateModel(
            name='WarrantyRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField(blank=True, max_length=50, null=True, verbose_name='User ID')),
                ('product_number_id', models.TextField(blank=True, max_length=50, null=True, verbose_name='Product Number')),
                ('serial_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Serial Number')),
                ('reseller_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Reseller Name')),
                ('purchase_date', models.DateField(blank=True, max_length=50, null=True, verbose_name='Purchase Date')),
                ('purchase_invoice', models.FileField(blank=True, max_length=50, null=True, upload_to='media/images/purchase_invoice', verbose_name='Purchase Invoice')),
            ],
        ),
    ]
