# Generated by Django 4.0.4 on 2022-05-10 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Warranty', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificates',
            name='order_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Order ID'),
        ),
        migrations.AlterField(
            model_name='certificates',
            name='product_configuration',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Product Configuration'),
        ),
        migrations.AlterField(
            model_name='certificates',
            name='user_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='warrantyextend',
            name='product_number_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Product Number'),
        ),
        migrations.AlterField(
            model_name='warrantyextend',
            name='user_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='User ID'),
        ),
        migrations.AlterField(
            model_name='warrantyregistration',
            name='product_number_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Product Number'),
        ),
        migrations.AlterField(
            model_name='warrantyregistration',
            name='user_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='User ID'),
        ),
    ]
