# Generated by Django 4.0.4 on 2022-05-11 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Warranty', '0002_alter_certificates_order_id_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Certificates',
            new_name='Certificate',
        ),
    ]
