# Generated by Django 4.0.4 on 2022-05-19 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Warranty', '0003_rename_certificates_certificate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warrantyextend',
            name='purchase_invoice',
            field=models.FileField(blank=True, max_length=50, null=True, upload_to='images/WarrantyExtend/purchase_invoice', verbose_name='Purchase Invoice'),
        ),
        migrations.AlterField(
            model_name='warrantyregistration',
            name='purchase_invoice',
            field=models.FileField(blank=True, max_length=50, null=True, upload_to='images/WarrantyRegistration/purchase_invoice', verbose_name='Purchase Invoice'),
        ),
    ]
